BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Frequency" (
	"id"	INTEGER,
	"frequency"	INTEGER NOT NULL,
	"power"	REAL NOT NULL,
	"datetime "	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "FrequencySample" (
	"id"	INTEGER,
	"fk"	INTEGER,
	"real"	REAL,
	"imag"	REAL,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("fk") REFERENCES ""
);
CREATE TABLE IF NOT EXISTS "Power" (
	"id"	INTEGER,
	"power"	REAL NOT NULL,
	"datetime"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "PowerFrequency" (
	"id"	INTEGER,
	"fk"	INTEGER,
	"frequency"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("fk") REFERENCES ""
);
COMMIT;
