BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "HighPowerFrequency" (
	"id"	INTEGER,
	"data"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "HighPowerSample" (
	"id"	INTEGER,
	"data"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
