# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

  # ALL JOBS implied: https://docs.readthedocs.io/en/stable/builds.html
  jobs:
    pre_install:
      - python --version
      - python -m pip install poetry
      - python -m poetry self add poetry-plugin-export
      - python -m poetry export -o req-docs.txt -E docs
    post_install:
      - python -m pip install -e .
      - python -m pip install pyyaml
    pre_build:
      - |
        for file in .github/workflows/*.yaml; do
          python ./scripts/visualize-ga-workflow.py "$file" > "./docs/$(basename "$file" .yaml)_mermaid.md"
        done
      - python ./scripts/visualize-dockerfile.py > ./docs/dockerfile_mermaid.md



# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf


# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
   install:
   - requirements: docs/requirements.txt
